# Generated by Django 5.1.3 on 2024-12-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='id',
        ),
        migrations.AddField(
            model_name='expense',
            name='srno',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
